
version: 2

sources:
  - name: northwind
    description: Data from northwind ERP
    database: curso-etl-101  
    schema: erp_northwind  
    tables:
      - name: orders
        freshness:
          warn_after:
            count: 5000
            period: day
          error_after:
            count: 10000
            period: day
        loaded_at_field: cast(order_date as timestamp)
        description: '{{ doc("orders_docs") }}'
        columns:
          - name: order_id
            description: Unique ID for this table
            tests:
              - unique
              - not_null
          - name: customer_id
            tests:
              - relationships:
                  to: source('northwind', 'customers')
                  field: customer_id

      - name: customers
        description: This table lists the customers from ERP Northwind
        columns:
          - name: customer_id
            description: Unique ID for this table
      - name: order_details
      - name: products
        description: This table lists the products from ERP Northwind
        columns:
          - name: product_id
            description: Unique ID for this table
      - name: suppliers
        description: This table lists the suppliers from ERP Northwind
        columns:
          - name: category_id
            description: Unique ID for this table

      - name: categories
        description: This table lists the categories from ERP Northwind
        columns:
          - name: supplier_id
            description: Unique ID for this table
