version: 2

sources:
  - name: northwind
    description: Data from northwind ERP
    database: curso-etl-101  
    schema: erp_northwind  
    tables:
      - name: orders
      - name: customers
        description: This table lists the customers from ERP Northwind
        columns:
          - name: customer_id
            description: Unique ID for this table
      - name: order_details
      - name: products
      - name: categories
      - name: suppliers